name: portfolio

dependencies:
  - python=3.7.0
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pip:
      - kaggle
      - tensorflow-cpu
      - keras
      - plotly
      - tqdm
      - tensorboard
